### ISSUE TITLE
erl-ie-evaluate and indentation by tabs

### ISSUE THREAD

**Issue by grepz** [massemanet/distel#44]
Hello,

In case indentation is done with spaces(sigh... don't ask), C-j in distel-ie-session buffer won't work as intendent, consuming part of value returned by erlang process.
It happens because indent-rigidly inserts tabs(and not 5, as stated in arguments), not spaces, so later delete-region erases part of returned value.
I think it can be fixed fast by changing(https://github.com/massemanet/distel/blob/master/elisp/distel-ie.el#L135)

``` elisp
(indent-rigidly beg (point) 5)
```

to

``` elisp
(indent-rigidly (+ beg 1) (point) 5)
```

And removing line https://github.com/massemanet/distel/blob/master/elisp/distel-ie.el#L137

**Comment by massemanet** [comment]
timed out...
