### ISSUE TITLE
Bug in erlext-encode-ieee-double

### ISSUE THREAD

**Issue by zwizwa** [massemanet/distel#66]
(erlext-encode-ieee-double 0.84)
gives
(0 13 112 163 215 10 61 112)

which in Erlang decodes to
1.869062041146049e-308

**Comment by leoliu** [comment]
Looks like this is my fault. I'll get to it soonish.

**Comment by leoliu** [comment]
@zwizwa Do you have time to test PR https://github.com/massemanet/distel/pull/67? Thanks for the bug report.

**Comment by zwizwa** [comment]
Hi Leo thanks for taking time for this. I've merged it and will remove my workaround soon. I'll send another message when I do.

**Comment by zwizwa** [comment]
Hi @leoliu I no longer see the issues. Thanks again. I see @massemanet already merged it.

**Comment by leoliu** [comment]
@zwizwa Thank you for the confirmation.
